### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, scandir '~/AppData\Local\Application Data'

### ISSUE THREAD

**Issue by yaroslavkrutiak** [belltown/roku-develop#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [roku-develop](https://github.com/belltown/roku-develop) package 0.1.12

### Stack Trace

Uncaught Error: EPERM: operation not permitted, scandir 'C:\Users\38097\AppData\Local\Application Data'

```
At fs.js:115

Error: EPERM: operation not permitted, scandir 'C:\Users\38097\AppData\Local\Application Data'
    at Object.readdirSync (fs.js:764:3)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:641:39)
    at Proxy.listSync (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:267975)
    at Directory.getEntriesSync (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:1145884)
    at Object.addFilesToArchive (/packages/roku-develop/lib/roku-develop.coffee:706:5)
    at Object.addFilesToArchive (/packages/roku-develop/lib/roku-develop.coffee:749:12)
    at Object.addFilesToArchive (/packages/roku-develop/lib/roku-develop.coffee:749:12)
    at Object.addFilesToArchive (/packages/roku-develop/lib/roku-develop.coffee:749:12)
    at /packages/roku-develop/lib/roku-develop.coffee:695:8
    at ReadFileContext.callback (/packages/roku-develop/lib/roku-develop.coffee:763:9)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
```

### Commands

```
     -9:19.3.0 core:confirm (div.package-detail)
     -7:00.0 roku-develop:deploy (input.hidden-input)
     -6:53.6.0 bracket-matcher:select-inside-brackets (input.hidden-input)
  2x -6:49.7.0 settings-view:open (input.hidden-input)
     -5:46.7.0 application:open-file (div.package-detail)
  2x -1:33.8.0 roku-develop:deploy (input.hidden-input)
```

### Non-Core Packages

```
roku-develop 0.1.12 
```

**Comment by belltown** [comment]
I'll look into it. Could you please show your roku-develop config settings: In the Atom menu: File > Config..., look under the "roku-develop" item (no need to include the passwords).

**Comment by belltown** [comment]
I think I see what happened here.

Your Roku "project directory" should be a folder containing all the code and data you will be uploading to your Roku device -- and ONLY the code and data you will be uploading to your Roku. The contents of your project directory should include your "source" directory, "components" directory, and "manifest" file, etc. The roku-develop Atom package will create a zip file of the contents of your project directory and upload it to your Roku. 

You therefore need to create a directory specific to your Roku project, and place your "components", "source", "manifest" file, etc. in that directory.

It looks like you have put your Roku project files directly in your Windows user home directory: "C:\Users\38097". This will result in your entire Windows user home directory being uploaded to your Roku. In this case, roku-develop crashes when trying to add "Application Data" to the zip file because of some Windows weirdness where that folder isn't a real folder but a "Junction" referencing its parent folder.

Instead, create a directory such as "C:\Users\38097\RokuChannel", and in this directory place your "component", "source", manifest", etc.

Sorry for the the inconvenience. If I come up with a new version of roku-develop, I'll put in some more user-friendly error-handling to deal with that case.
